nohup python crawl.py 0 >> 0.log &
nohup python crawl.py 1 >> 1.log &
nohup python crawl.py 2 >> 2.log &
nohup python crawl.py 3 >> 3.log &
nohup python crawl.py 4 >> 4.log &
nohup python crawl.py 5 >> 5.log &
nohup python crawl.py 6 >> 6.log &
nohup python crawl.py 7 >> 7.log &
nohup python crawl.py 8 >> 8.log &
nohup python crawl.py 9 >> 9.log &
