nohup python crawl.py 0 >> 0.log &
nohup python crawl.py 1 >> 1.log &
nohup python crawl.py 2 >> 2.log &
nohup python crawl.py 3 >> 3.log &
nohup python crawl.py 4 >> 4.log &
nohup python crawl.py 5 >> 5.log &
nohup python crawl.py 6 >> 6.log &
nohup python crawl.py 7 >> 7.log &
nohup python crawl.py 8 >> 8.log &
nohup python crawl.py 9 >> 9.log &
nohup python crawl.py 10 >> 10.log &
nohup python crawl.py 11 >> 11.log &
nohup python crawl.py 12 >> 12.log &
nohup python crawl.py 13 >> 13.log &
nohup python crawl.py 14 >> 14.log &
nohup python crawl.py 15 >> 15.log &
nohup python crawl.py 16 >> 16.log &
nohup python crawl.py 17 >> 17.log &
nohup python crawl.py 18 >> 18.log &
nohup python crawl.py 19 >> 19.log &
